MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
BOOTLOADER = caterina
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

EXTRAKEY_ENABLE = yes      # Audio control and System control(+450)
TAP_DANCE_ENABLE = no
SPLIT_KEYBOARD = yes
NO_USB_STARTUP_CHECK = yes
LTO_ENABLE = yes
KEYBOARD_SHARED_EP = yes
