#include QMK_KEYBOARD_H

#define _COLEMAK 0
#define _FUNC 1
#define _NUMPAD 2
#define _SYMBOLS 3

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
   [_COLEMAK] = LAYOUT(KC_Q,KC_W,KC_F,KC_P,KC_G,KC_J,KC_L,KC_U,KC_Y,KC_SCLN,KC_A,KC_R,KC_S,KC_T,KC_D,KC_H,KC_N,KC_E,KC_I,KC_O,KC_Z,KC_X,KC_C,KC_V,KC_B,KC_K,KC_M,KC_COMM,KC_DOT,LT(_FUNC, KC_SLSH), KC_ESC,   KC_DEL,  KC_LALT, KC_LSFT, LCTL_T( KC_TAB),  KC_LGUI, LT(_NUMPAD, KC_ENTER), KC_BSPC,  LT(_SYMBOLS, KC_SPACE), KC_MINS, KC_QUOT, KC_EQUAL),
   [_FUNC] = LAYOUT(KC_F9,KC_F10,KC_F11,KC_F12,KC_VOLU,KC_DOWN,KC_RIGHT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_F5,KC_F6,KC_F7,KC_F8,KC_MPLY,KC_LEFT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_F1,KC_F2,KC_F3,KC_F4,KC_VOLD,KC_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RESET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RESET),
   [_NUMPAD] = LAYOUT(KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_7,KC_8,KC_9,KC_SLSH,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_4,KC_5,KC_6,KC_ASTR,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_1,KC_2,KC_3,KC_MINS,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_0,KC_0,KC_DOT,KC_PLUS),
   [_SYMBOLS] = LAYOUT(KC_EXLM,KC_AT,KC_HASH,KC_DLR,KC_PERC,KC_CIRC,KC_AMPR,KC_ASTR,KC_LPRN,KC_RPRN,KC_GRV,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LBRC,KC_RBRC,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_SLSH,KC_PIPE,KC_BSLS,KC_LCBR,KC_RCBR,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT)
};

